(add-to-list 'load-path  "/cygwin/home/paramjit/userconfig/common/emacs")
(load "/cygwin/home/paramjit/userconfig/common/etc/emacs.el")
(setq ispell-program-name "C:/Program Files (x86)/Aspell/bin/aspell.exe")
(require 'tramp)
(setq tramp-default-method "plink")
