[[ -z $CONF ]] && source ~/.profile NO_BASHRC
[[ -a $CONF/common/bashrc ]] && source $CONF/common/bashrc
[[ -a $CONF/site/$SITE/bashrc ]] && source $CONF/site/$SITE/bashrc
[[ -a $CONF/plat/$PLAT/bashrc ]] && source $CONF/plat/$PLAT/bashrc
[[ -a $CONF/host/$HOST/bashrc ]] && source $CONF/host/$HOST/bashrc
