# ---- aliases

alias ls='ls -bF --color=auto'  # "b" will show control characters as '?'
                                # "F" will show a trailing "/" after directories
                                # and a "*" after executables
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ci='echo Do you REALLY want to run RCS?'   # type 'vi' NOT 'ci' !!
alias mc='echo Do you REALLY want to run Midnight Commander?'

# ---- terminal settings

unset MAILCHECK
umask 0002

# ---- bash options & enhancements

set -o ignoreeof        # ignore ^D to exit shell
set -o notify           # report change in jobs' status

shopt -s cdspell
shopt -s checkhash
shopt -s checkwinsize
shopt -s histappend
shopt -s no_empty_cmd_completion

if [ -t 0 ]; then       # if stdin is a terminal
    stty -ixon          # no flow control
fi

export PS1="\h(\!)[\w]\\\$ "
export PROMPT_COMMAND="history -a"
export HISTCONTROL=ignorespace
export HISTSIZE=2000
export HISTFILESIZE=5000

WTITLE="\u@\h: \w"
VTE_CMD=""
function pso_prompt_cmd() {
  history -a
  echo -ne "\033]0;${WTITLE@P}\007"
  $VTE_CMD
}

case $TERM in
    xterm*|screen)
        # PS1="\[\033]0;\u@\h:\w\007\]\h(\!)[\w]\\\$ "
        PROMPT_COMMAND=`pso_prompt_cmd`
        ;;
    *)
        PROMPT_COMMAND="history -a"
        ;;
esac

if [[ -f /etc/profile.d/bash_completion.sh ]]; then
    source /etc/profile.d/bash_completion.sh
fi

if [[ -d $HOME/sw/google-cloud-sdk ]]; then
    source $HOME/sw/google-cloud-sdk/completion.bash.inc
fi

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
    VTE_CMD="__vte_osc7"
fi

if which powerline-daemon >/dev/null 2>&1 ; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  . /usr/share/powerline/bash/powerline.sh
fi
