# ---- aliases

alias ls='ls -bF --color=auto'  # "b" will show control characters as '?'
                                # "F" will show a trailing "/" after directories
                                # and a "*" after executables

alias ci='echo Do you REALLY want to run RCS?'   # type 'vi' NOT 'ci' !!
alias mc='echo Do you REALLY want to run Midnight Commander?'

# ---- terminal settings

unset MAILCHECK
umask 0002

# ---- bash options

set -o ignoreeof        # ignore ^D to exit shell
set -o notify           # report change in jobs' status

shopt -s cdspell
shopt -s checkhash
shopt -s checkwinsize
shopt -s histappend
shopt -s no_empty_cmd_completion

if [ -t 0 ]; then       # if stdin is a terminal
    stty -ixon          # no flow control
fi    

case $TERM in
    xterm*|screen)
        PS1="\[\033]0;\u@\h:\w\007\]$PS1"
        ;;
esac
